#!/bin/bash
# Download script for Priority 3 assets
# Run this from your browser while signed into Google Drive

set -e

DRIVE_ROOT="https://drive.google.com/drive/folders/1qjhACfUvawpuQdpV8hdHVglGHIFC6UMu"
DOWNLOAD_DIR="$HOME/Downloads/second-movement-assets"
ASSET_DIR="$HOME/repos/second-movement/assets"

echo "📦 Second Movement - Asset Download Instructions"
echo "================================================"
echo ""
echo "Since Google Drive requires authentication, here's what to do:"
echo ""
echo "OPTION 1: Manual Download via Browser"
echo "--------------------------------------"
echo "1. Open: $DRIVE_ROOT"
echo "2. Sign in to Google Drive"
echo "3. Download these folders/files:"
echo ""
echo "   TIER 1 - Essential:"
echo "   ✓ 30 Wireframe Vectors Pack/"
echo "   ✓ Frequencies Scan Texture Pack/ (pick 3-4 files)"
echo "   ✓ font/@daniel schriër/Heritage Display/"
echo ""
echo "   TIER 2 - Recommended:"
echo "   ✓ @GFXDatabase/X10 Thermo Texture Pack V1/JPG/ (2 files)"
echo "   ✓ @TypeDuNord/Designer Dingbats/"
echo "   ✓ Divinity - gfx kit/.../_ texture/ (3 files)"
echo ""
echo "4. Save to: $DOWNLOAD_DIR"
echo "5. Run: ./extract_assets.sh"
echo ""
echo "OPTION 2: Using gdown (if folder sharing allows)"
echo "-----------------------------------------------"
echo "Install: pip3 install gdown"
echo ""
echo "# Try downloading entire folder (may not work for shared folders)"
echo "gdown --folder '$DRIVE_ROOT' -O '$DOWNLOAD_DIR'"
echo ""
echo "OPTION 3: Sign in via browser tool"
echo "-----------------------------------"
echo "Tell me to sign in and I'll download via browser automation"
echo ""
